language: php

php:
    - 7.2
    - nigtly # 7.3?

install:
    - composer update

script:
    # run tests for tested posts (with "tested: true" in header configuration)
    - vendor/bin/phpunit

    # static analysis
    - composer check-cs
    - composer phpstan

    # dump contributors before deploy
    - |
        if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
          bin/console dump-contributors
        fi

    # test that website is generated
    - vendor/bin/statie generate source

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

after_deploy:
    # tweets posts
    - |
      if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
        packages/StatieTweetPublisher/bin/publish-new-tweet
      fi

notifications:
    email:
        on_success: never
        on_failure: always
